version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tiketq
      POSTGRES_PASSWORD: tiketqpass
      POSTGRES_DB: tiketqdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 run:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://tiketq:tiketqpass@db:5432/tiketqdb
    depends_on:
      - db

volumes:
  postgres_data:
